---
# IF a SPOT resource is specified AND the 'alt_disk_install' fileset is not installed
# THEN this task will install the 'alt_disk_install' fileset
#
# IF a SPOT resource is NOT specified and will be automatically created
# THEN this task will automatically install the 'alt_disk_install' fileset
- name: "Add 'bos.alt_disk_install.rte fileset to {{ spot }}"
  block:
    - command: >
        nim -o cust -a lpp_source={{ lpp_source }} 
        -a filesets=bos.alt_disk_install.rte {{ spot }}
      register: spot_fileset_install
      
    - fail:
        msg: >
          Installation of 'bos.alt_disk_install.rte' on {{ spot }} failed
      when: "spot_fileset_install is failed"

    - debug:
        msg: >
          'bos.alt_disk_install.rte' fileset installed in {{ spot }}
