---
- name: "BOS install using mksysb image"
  hosts: nimserver
  gather_facts: no
  vars:
    vm_targets: quimby01
    res_group: basic_res_grp
  tasks:

    - name: Install using group resource
      nim:
        action: 'bos_inst'
        targets: "{{ vm_targets }}"
        group: "{{ res_group }}"
        description: 'NIM -o bos_inst -a source=mksysb'
      register: nim_output
    - debug: var=nim_output
