---
- name: "LVOL on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    host_name: all
    vg_name: rootvg
    lv_name: testlv
    size_val: "64M"
    increase_size_val: 

  collections:
    ibm.power_aix
  tasks:
    - name: Create a logical volume of 64M
      lvol:
        state: present
        vg: "{{vg_name}}"
        lv: testrootlv
        size: "{{size_val}}"
    - name: Create a logical volume of 10 logical partitions with disks hdisk0 and hdisk1
      lvol:
        state: present
        vg: "{{vg_name}}"
        lv: test2lv
        size: "{{size_val}}"
        pv_list: hdisk0, hdisk1
    - name: Create a logical volume of 32M with a minimum placement policy
      lvol:
        state: present
        vg: "{{vg_name}}"
        lv: test4lv
        size: "32M"
        policy: minimum
    - name: Create a logical volume with extra options like mirror pool
      lvol:
        state: present
        vg: "{{vg_name}}"
        lv: "{{lv_name}}"
        size: "{{size_val}}"
        extra_opts: -m copy1=poolA -m copy2=poolB
    - name: Extend a logical volume by 1G
      lvol:
        state: present
        vg: "{{vg_name}}"
        lv: "{{lv_name}}"
        size: "+1G"
    - name: Rename a logical volume
      lvol:
        state: present
        vg: "{{vg_name}}"
        lv: "{{lv_name}}"
        lv_new_name: renamedlv
    - name: Remove the logical volume
      lvol:
        state: absent
        lv: testrootlv