---
- name: "NIM check on AIX playbook"
  hosts: nim
  gather_facts: no

  tasks:

    - name: "AIX NIM"
      nim:
        action: 'check'
        description: 'NIM check'
      register: nim_output
    - debug: var=nim_output

