---
name: run ibm.power_aix collection linting tests

# run sanity test during pull request to dev-collection
on:
  pull_request:
    branches: [ dev-collection ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ########################################################################
  # module linting test
  # - makes sure that the collection conforms with PEP8 coding style
  # standards
  ########################################################################
  module-linting-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/ibm/power_aix
    strategy:
      matrix:
        ansible-version: ['2.9']
        python-version: ['3.11.0']

    name: running module linting test
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        path: ansible_collections/ibm/power_aix
      
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: install linting test requirements
      run: |
        python -m pip install --upgrade pip
        make install-ansible ANSIBLE_VERSION=${{ matrix.ansible-version }}
        make install-sanity-test-requirements

    - name: run pep8 coding style linter
      run: |
        make module-lint

  ########################################################################
  # role linting test
  # - makes sure that the collection conforms with PEP8 coding style
  # standards
  ########################################################################
  role-linting-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/ibm/power_aix
    strategy:
      matrix:
        ansible-version: ['2.9']
        python-version: ['3.11.0']

    name: running role linting test
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        path: ansible_collections/ibm/power_aix
      
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: install linting test requirements
      run: |
        python -m pip install --upgrade pip
        make install-ansible ANSIBLE_VERSION=${{ matrix.ansible-version }}
        make install-sanity-test-requirements

    - name: run pep8 coding style linter
      run: |
        make role-lint
