---
name: run ibm.power_aix collection sanity tests

# run sanity test during pull request to dev-collection
on:
  pull_request:
    branches: [ dev-collection ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ########################################################################
  # porting test
  # - makes sure that the collection is properly ported for python3
  ########################################################################
  porting-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/ibm/power_aix
    strategy:
      matrix:
        ansible-version: ['2.9']
        python-version: ['3.11.0']

    name: running python3 porting test
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        path: ansible_collections/ibm/power_aix
      
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: install linting test requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint==2.10.*

    - name: run python3 porting linter
      run: |
        make porting 
